# 语言字典
language_map = {
    "zh-CN": "cn",
    "zh-TW": "tw",
    "en": "en",
    "German": "de",
    "es": "es",
    "fr": "fr",
    "Japanese": "jp",
    "Portuguese": "pt",
    "ru": "ru",
}
# 数据库字段
fields = [
    "id",
    "name",
    "tag_name",
    "category_name",
    "url",
    "thumbnail_url",
    "image_url",
    "collection_time",
    "star_rating",
    "title_en",
    "content_en",
    "detail_en",
    "introduction_en",
    "website_data_en",
    "title_cn",
    "content_cn",
    "introduction_cn",
    "website_data_cn",
    "detail_cn",
    "website_data_de",
    "website_data_es",
    "website_data_fr",
    "website_data_jp",
    "website_pt",
    "website_data_ru",
    "website_data_tw",
    "detail_de",
    "detail_es",
    "detail_fr",
    "detail_jp",
    "detail_pt",
    "detail_ru",
    "detail_tw",
    "introduction_de",
    "introduction_es",
    "introduction_fr",
    "introduction_jp",
    "introduction_pt",
    "introduction_tw",
    "introduction_ru",
    "title_de",
    "title_es",
    "title_fr",
    "title_jp",
    "title_pt",
    "title_ru",
    "title_tw",
    "content_de",
    "content_es",
    "content_fr",
    "content_pt",
    "content_jp",
    "content_ru",
    "content_tw"
]
