INSERT INTO "public"."navigation_tag" 
("id", "code", "name_en", "name_cn", "category_name", "name_de", "name_es", "name_fr", "name_jp", "name_pt", "name_ru", "name_tw") VALUES 
('1', 'Datacenter', 'Datacenter', '数据中心', 'proxy', 'Rechenzentrum', 'Centro de datos', 'Centre de données', 'データセンター', 'Centro de dados', 'Дата-центр', '數據中心'), 
('2', 'Dedicated', 'Dedicated', '专用', 'proxy', 'Dediziert', 'Dedicado', 'Dédié', '専用', 'Dedicado', 'Выделенный', '專用'), 
('3', 'Mobile', 'Mobile', '移动', 'proxy', 'Mobil', 'Móvil', 'Mobile', 'モバイル', 'Móvel', 'Мобильный', '移動'), 
('4', 'Residential', 'Residential', '住宅', 'proxy', 'Wohn', 'Residencial', 'Résidentiel', '住宅', 'Residencial', 'Резиденциальный', '住宅'), 
('5', 'Rotating', 'Rotating', '轮换代理', 'proxy', 'Rotierend', 'Rotatorio', 'Rotatif', '回転', 'Rotativo', 'Ротационный', '輪替'), 
('6', 'SOCKS5', 'SOCKS5', 'SOCKS5', 'proxy', 'SOCKS5', 'SOCKS5', 'SOCKS5', 'SOCKS5', 'SOCKS5', 'SOCKS5', 'SOCKS5'), 
('7', 'ISP', 'ISP', 'ISP', 'proxy', 'ISP', 'ISP', 'ISP', 'ISP', 'ISP', 'ISP', 'ISP'), 
('8', 'IPV4', 'IPV4', 'IPV4', 'proxy', 'IPV4', 'IPV4', 'IPV4', 'IPV4', 'IPV4', 'IPV4', 'IPV4'), 
('9', 'Shared', 'Shared', '共享', 'proxy', 'Geteilt', 'Compartido', 'Partagé', '共有', 'Compartilhado', 'Общий', '共享'), 
('10', 'Premium', 'Premium', '高级', 'proxy', 'Premium', 'Premium', 'Premium', 'プレミアム', 'Premium', 'Премиум', '高級'), 
('11', 'Private', 'Private', '私人', 'proxy', 'Privat', 'Privado', 'Privé', 'プライベート', 'Privado', 'Приватный', '私人'), 
('12', 'Paid', 'Paid', '付费', 'proxy', 'Bezahlt', 'Pagado', 'Payant', '有料', 'Pago', 'Платный', '付費'), 
('13', 'Free', 'Free', '免费', 'proxy', 'Kostenlos', 'Gratis', 'Gratuit', '無料', 'Grátis', 'Бесплатный', '免費'), 
('14', 'Australia', 'Australia', '澳大利亚', 'proxy', 'Australien', 'Australia', 'Australie', 'オーストラリア', 'Austrália', 'Австралия', '澳洲'), 
('15', 'Argentina', 'Argentina', '阿根廷', 'proxy', 'Argentinien', 'Argentina', 'Argentine', 'アルゼンチン', 'Argentina', 'Аргентина', '阿根廷'), 
('16', 'Brazil', 'Brazil', '巴西', 'proxy', 'Brasilien', 'Brasil', 'Brésil', 'ブラジル', 'Brasil', 'Бразилия', '巴西'), 
('17', 'Canada', 'Canada', '加拿大', 'proxy', 'Kanada', 'Canadá', 'Canada', 'カナダ', 'Canadá', 'Канада', '加拿大'), 
('18', 'China', 'China', '中国', 'proxy', 'China', 'China', 'Chine', '中国', 'China', 'Китай', '中國'), 
('19', 'France', 'France', '法国', 'proxy', 'Frankreich', 'Francia', 'France', 'フランス', 'França', 'Франция', '法國'), 
('20', 'Germany', 'Germany', '德国', 'proxy', 'Deutschland', 'Alemania', 'Allemagne', 'ドイツ', 'Alemanha', 'Германия', '德國'), 
('21', 'India', 'India', '印度', 'proxy', 'Indien', 'India', 'Inde', 'インド', 'Índia', 'Индия', '印度'), 
('22', 'Israel', 'Israel', '以色列', 'proxy', 'Israel', 'Israel', 'Israël', 'イスラエル', 'Israel', 'Израиль', '以色列'), 
('23', 'Italy', 'Italy', '意大利', 'proxy', 'Italien', 'Italia', 'Italie', 'イタリア', 'Itália', 'Италия', '意大利'), 
('24', 'Indonesia', 'Indonesia', '印度尼西亚', 'proxy', 'Indonesien', 'Indonesia', 'Indonésie', 'インドネシア', 'Indonésia', 'Индонезия', '印尼'), 
('25', 'Netherlands', 'Netherlands', '荷兰', 'proxy', 'Niederlande', 'Países Bajos', 'Pays-Bas', 'オランダ', 'Países Baixos', 'Нидерланды', '荷蘭'), 
('26', 'New Zealand', 'New Zealand', '新西兰', 'proxy', 'Neuseeland', 'Nueva Zelanda', 'Nouvelle-Zélande', 'ニュージーランド', 'Nova Zelândia', 'Новая Зеландия', '紐西蘭'), 
('27', 'Poland', 'Poland', '波兰', 'proxy', 'Polen', 'Polonia', 'Pologne', 'ポーランド', 'Polônia', 'Польша', '波蘭'), 
('28', 'Pakistan', 'Pakistan', '巴基斯坦', 'proxy', 'Pakistan', 'Pakistán', 'Pakistan', 'パキスタン', 'Paquistão', 'Пакистан', '巴基斯坦'), 
('29', 'Spain', 'Spain', '西班牙', 'proxy', 'Spanien', 'España', 'Espagne', 'スペイン', 'Espanha', 'Испания', '西班牙'), 
('30', 'Sweden', 'Sweden', '瑞典', 'proxy', 'Schweden', 'Suecia', 'Suède', 'スウェーデン', 'Suécia', 'Швеция', '瑞典'), 
('31', 'United Kingdom', 'United Kingdom', '英国', 'proxy', 'Vereinigtes Königreich', 'Reino Unido', 'Royaume-Uni', 'イギリス', 'Reino Unido', 'Великобритания', '英國'), 
('32', 'United States', 'United States', '美国', 'proxy', 'Vereinigte Staaten', 'Estados Unidos', 'États-Unis', 'アメリカ', 'Estados Unidos', 'Соединенные Штаты', '美國'), 
('33', 'Ukraine', 'Ukraine', '乌克兰', 'proxy', 'Ukraine', 'Ucrania', 'Ukraine', 'ウクライナ', 'Ucrânia', 'Украина', '烏克蘭'), 
('34', 'Vietnam', 'Vietnam', '越南', 'proxy', 'Vietnam', 'Vietnam', 'Vietnam', 'ベトナム', 'Vietnã', 'Вьетнам', '越南'), 
('35', 'Russia', 'Russia', '俄罗斯', 'proxy', 'Russland', 'Rusia', 'Russie', 'ロシア', 'Rússia', 'Россия', '俄羅斯'), 
('36', 'Japan', 'Japan', '日本', 'proxy', 'Japan', 'Japón', 'Japon', '日本', 'Japão', 'Япония', '日本'), 
('37', 'South Korea', 'South Korea', '韩国', 'proxy', 'Südkorea', 'Corea del Sur', 'Corée du Sud', '韓国', 'Coreia do Sul', 'Южная Корея', '韓國'), 
('38', 'Mexico', 'Mexico', '墨西哥', 'proxy', 'Mexiko', 'México', 'Mexique', 'メキシコ', 'México', 'Мексика', '墨西哥'), 
('39', 'Austria', 'Austria', '奥地利', 'proxy', 'Österreich', 'Austria', 'Autriche', 'オーストリア', 'Áustria', 'Австрия', '奧地利'), 
('40', 'Belgium', 'Belgium', '比利时', 'proxy', 'Belgien', 'Bélgica', 'Belgique', 'ベルギー', 'Bélgica', 'Бельгия', '比利時'), 
('41', 'Bulgaria', 'Bulgaria', '保加利亚', 'proxy', 'Bulgarien', 'Bulgaria', 'Bulgarie', 'ブルガリア', 'Bulgária', 'Болгария', '保加利亞'), 
('42', 'Croatia', 'Croatia', '克罗地亚', 'proxy', 'Kroatien', 'Croacia', 'Croatie', 'クロアチア', 'Croácia', 'Хорватия', '克羅地亞'), 
('43', 'Cyprus', 'Cyprus', '塞浦路斯', 'proxy', 'Zypern', 'Chipre', 'Chypre', 'キプロス', 'Chipre', 'Кипр', '塞浦路斯'), 
('44', 'Czech Republic', 'Czech Republic', '捷克共和国', 'proxy', 'Tschechische Republik', 'República Checa', 'République tchèque', 'チェコ', 'República Tcheca', 'Чехия', '捷克共和國'), 
('45', 'Denmark', 'Denmark', '丹麦', 'proxy', 'Dänemark', 'Dinamarca', 'Danemark', 'デンマーク', 'Dinamarca', 'Дания', '丹麥'), 
('46', 'Estonia', 'Estonia', '爱沙尼亚', 'proxy', 'Estland', 'Estonia', 'Estonie', 'エストニア', 'Estônia', 'Эстония', '愛沙尼亞'), 
('47', 'Finland', 'Finland', '芬兰', 'proxy', 'Finnland', 'Finlandia', 'Finlande', 'フィンランド', 'Finlândia', 'Финляндия', '芬蘭'), 
('48', 'Greece', 'Greece', '希腊', 'proxy', 'Griechenland', 'Grecia', 'Grèce', 'ギリシャ', 'Grécia', 'Греция', '希臘'), 
('49', 'Hungary', 'Hungary', '匈牙利', 'proxy', 'Ungarn', 'Hungría', 'Hongrie', 'ハンガリー', 'Hungria', 'Венгрия', '匈牙利'), 
('50', 'Ireland', 'Ireland', '爱尔兰', 'proxy', 'Irland', 'Irlanda', 'Irlande', 'アイルランド', 'Irlanda', 'Ирландия', '愛爾蘭'), 
('51', 'Latvia', 'Latvia', '拉脱维亚', 'proxy', 'Lettland', 'Letonia', 'Lettonie', 'ラトビア', 'Letônia', 'Латвия', '拉脫維亞'), 
('52', 'Lithuania', 'Lithuania', '立陶宛', 'proxy', 'Litauen', 'Lituania', 'Lituanie', 'リトアニア', 'Lituânia', 'Литва', '立陶宛'), 
('53', 'Luxembourg', 'Luxembourg', '卢森堡', 'proxy', 'Luxemburg', 'Luxemburgo', 'Luxembourg', 'ルクセンブルク', 'Luxemburgo', 'Люксембург', '盧森堡'), 
('54', 'Malta', 'Malta', '马耳他', 'proxy', 'Malta', 'Malta', 'Malte', 'マルタ', 'Malta', 'Мальта', '馬爾他'), 
('55', 'Portugal', 'Portugal', '葡萄牙', 'proxy', 'Portugal', 'Portugal', 'Portugal', 'ポルトガル', 'Portugal', 'Португалия', '葡萄牙'), 
('56', 'Romania', 'Romania', '罗马尼亚', 'proxy', 'Rumänien', 'Rumania', 'Roumanie', 'ルーマニア', 'Romênia', 'Румыния', '羅馬尼亞'), 
('57', 'Slovakia', 'Slovakia', '斯洛伐克', 'proxy', 'Slowakei', 'Eslovaquia', 'Slovaquie', 'スロバキア', 'Eslováquia', 'Словакия', '斯洛伐克'), 
('58', 'Slovenia', 'Slovenia', '斯洛文尼亚', 'proxy', 'Slowenien', 'Eslovenia', 'Slovénie', 'スロベニア', 'Eslovênia', 'Словения', '斯洛文尼亞'), 
('59', 'Iceland', 'Iceland', '冰岛', 'proxy', 'Island', 'Islandia', 'Islande', 'アイスランド', 'Islândia', 'Исландия', '冰島'), 
('60', 'Liechtenstein', 'Liechtenstein', '列支敦士登', 'proxy', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'リヒテンシュタイン', 'Liechtenstein', 'Лихтенштейн', '列支敦士登'), 
('61', 'Norway', 'Norway', '挪威', 'proxy', 'Norwegen', 'Noruega', 'Norvège', 'ノルウェー', 'Noruega', 'Норвегия', '挪威'), 
('62', 'Amazon', 'Amazon', '亚马逊', 'proxy', 'Amazon', 'Amazon', 'Amazon', 'アマゾン', 'Amazon', 'Amazon', 'Amazon'), 
('63', 'eBay', 'eBay', 'eBay', 'proxy', 'eBay', 'eBay', 'eBay', 'eBay', 'eBay', 'eBay', 'eBay'), 
('64', 'Facebook', 'Facebook', 'Facebook', 'proxy', 'Facebook', 'Facebook', 'Facebook', 'Facebook', 'Facebook', 'Facebook', 'Facebook'), 
('65', 'Instagram', 'Instagram', 'Instagram', 'proxy', 'Instagram', 'Instagram', 'Instagram', 'Instagram', 'Instagram', 'Instagram', 'Instagram'), 
('66', 'Reddit', 'Reddit', 'Reddit', 'proxy', 'Reddit', 'Reddit', 'Reddit', 'Reddit', 'Reddit', 'Reddit', 'Reddit'), 
('67', 'YouTube', 'YouTube', 'YouTube', 'proxy', 'YouTube', 'YouTube', 'YouTube', 'YouTube', 'YouTube', 'YouTube', 'YouTube'), 
('68', 'Discord', 'Discord', 'Discord', 'proxy', 'Discord', 'Discord', 'Discord', 'Discord', 'Discord', 'Discord', 'Discord'), 
('69', 'Telegram', 'Telegram', 'Telegram', 'proxy', 'Telegram', 'Telegram', 'Telegram', 'Telegram', 'Telegram', 'Telegram', 'Telegram'), 
('70', 'Twitter', 'Twitter', 'Twitter', 'proxy', 'Twitter', 'Twitter', 'Twitter', 'Twitter', 'Twitter', 'Twitter', 'Twitter'), 
('71', 'TikTok', 'TikTok', 'TikTok', 'proxy', 'TikTok', 'TikTok', 'TikTok', 'TikTok', 'TikTok', 'TikTok', 'TikTok'), 
('72', 'Pinterest', 'Pinterest', 'Pinterest', 'proxy', 'Pinterest', 'Pinterest', 'Pinterest', 'Pinterest', 'Pinterest', 'Pinterest', 'Pinterest'), 
('73', 'Sneaker', 'Sneaker', '运动鞋', 'proxy', 'Sneaker', 'Zapatillas', 'Sneaker', 'スニーカー', 'Tênis', 'Кроссовки', '球鞋'), 
('74', 'Scraping', 'Scraping', '抓取', 'proxy', 'Scraping', 'Raspado', 'Grattage', 'スクレイピング', 'Raspagem', 'Парсинг', '網頁抓取'), 
('75', 'SEO', 'SEO', 'SEO', 'proxy', 'SEO', 'SEO', 'SEO', 'SEO', 'SEO', 'SEO', 'SEO'), 
('76', 'Social Media', 'Social Media', '社交媒体', 'proxy', 'Soziale Medien', 'Redes Sociales', 'Médias sociaux', 'ソーシャルメディア', 'Mídias Sociais', 'Социальные сети', '社交媒體'), 
('77', 'Craigslist', 'Craigslist', 'Craigslist', 'proxy', 'Craigslist', 'Craigslist', 'Craigslist', 'Craigslist', 'Craigslist', 'Craigslist', 'Craigslist'), 
('78', 'Google', 'Google', 'Google', 'proxy', 'Google', 'Google', 'Google', 'Google', 'Google', 'Google', 'Google'), 
('79', 'AI常用工具', 'Common AI Tools', 'AI常用工具', 'AI工具', 'Allgemeine KI-Tools', 'Herramientas de IA comunes', 'Outils IA communs', '共通AIツール', 'Ferramentas de IA comuns', 'Общие AI-инструменты', 'AI常用工具'), 
('80', 'AI写作工具', 'AI Writing Tool', 'AI写作工具', 'AI工具', 'KI-Schreibwerkzeug', 'Herramienta de escritura de IA', 'Outil décriture IA', 'AIライティングツール', 'Ferramenta de escrita de IA', 'Инструмент для написания на AI', 'AI 寫作工具'), 
('81', 'AI视频工具', 'AI Video Tools', 'AI视频工具', 'AI工具', 'KI-Video-Tools', 'Herramientas de vídeo de IA', 'Outils vidéo IA', 'AIビデオツール', 'Ferramentas de vídeo de IA', 'Видео-инструменты AI', 'AI 視頻工具'), 
('82', 'AI设计工具', 'AI Design Tools', 'AI设计工具', 'AI工具', 'KI-Design-Tools', 'Herramientas de diseño de IA', 'Outils de conception IA', 'AIデザインツール', 'Ferramentas de design de IA', 'Инструменты для проектирования на AI', 'AI 設計工具'), 
('83', 'AI编程工具', 'AI Programming Tools', 'AI编程工具', 'AI工具', 'KI-Programmierwerkzeuge', 'Herramientas de programación de IA', 'Outils de programmation IA', 'AIプログラミングツール', 'Ferramentas de programação de IA', 'Инструменты программирования на AI', 'AI 程式設計工具'), 
('84', '常用工具', 'Common Tools', '常用工具', '实用工具', 'Alltagswerkzeuge', 'Herramientas comunes', 'Outils courants', '一般的なツール', 'Ferramentas comuns', 'Обычные инструменты', '常用工具'), 
('85', '推荐工具', 'Recommended Tools', '推荐工具', '实用工具', 'Empfohlene Werkzeuge', 'Herramientas recomendadas', 'Outils recommandés', '推奨ツール', 'Ferramentas recomendadas', 'Рекомендуемые инструменты', '推荐工具'), 
('86', '常用网址', 'Common Websites', '常用网址', '实用工具', 'Häufige Webseiten', 'Sitios web comunes', 'Sites web courants', '一般的なウェブサイト', 'Sites comuns', 'Распространенные сайты', '常用網址'), 
('87', '效率工具', 'Efficiency Tools', '效率工具', '实用工具', 'Effizienzwerkzeuge', 'Herramientas de eficiencia', 'Outils d'efficacité', '効率ツール', 'Ferramentas de eficiência', 'Инструменты эффективности', '效率工具'), 
('88', '短链生成工具', 'URL Shortener', '短链生成工具', '实用工具', 'URL-Verkürzer', 'Acortador de URL', 'Raccourciseur d''URL', 'URL短縮ツール', 'Encurtador de URL', 'Сократитель URL', '短網址生成工具'), 
('89', 'SCRM工具', 'SCRM Tools', 'SCRM工具', '实用工具', 'SCRM-Tools', 'Herramientas SCRM', 'Outils de SCRM', 'SCRMツール', 'Ferramentas SCRM', 'Инструменты SCRM', 'SCRM工具'), 
('90', '筛号工具', 'Phone Filtering Tools', '筛号工具', '实用工具', 'Telefonfilterwerkzeuge', 'Herramientas de filtrado de teléfonos', 'Outils de filtrage des appels', '電話フィルタリングツール', 'Ferramentas de filtragem de telefone', 'Инструменты фильтрации телефонов', '篩選號碼工具'), 
('91', '全球新闻', 'Global News', '全球新闻', '跨境资讯', 'Globale Nachrichten', 'Noticias globales', 'Actualités mondiales', 'グローバルニュース', 'Notícias globais', 'Глобальные новости', '全球新聞'), 
('92', '中国论坛', 'China Forum', '中国论坛', '跨境资讯', 'China-Forum', 'Foro de China', 'Forum de la Chine', '中国フォーラム', 'Fórum da China', 'Форум Китая', '中國論壇'), 
('93', '全球论坛', 'Global Forum', '全球论坛', '跨境资讯', 'Globales Forum', 'Foro Global', 'Forum mondial', 'グローバルフォーラム', 'Fórum Global', 'Глобальный форум', '全球論壇'), 
('94', 'Affliate联盟', 'Affiliate Alliance', 'Affliate联盟', '跨境资讯', 'Affiliate-Allianz', 'Alianza de Afiliados', 'Alliance des Affiliés', 'アフィリエイトアライアンス', 'Aliança de Afiliados', 'Аффилированный альянс', 'Affliate聯盟'), 
('95', '社交媒体', 'Social Media', '社交媒体', '跨境推广', 'Soziale Medien', 'Redes Sociales', 'Médias sociaux', 'ソーシャルメディア', 'Mídias sociais', 'Социальные медиа', '社交媒體'), 
('96', '社交营销', 'Social Marketing', '社交营销', '跨境推广', 'Sozialmarketing', 'Marketing Social', 'Marketing social', 'ソーシャルマーケティング', 'Marketing social', 'Социальный маркетинг', '社交營銷'), 
('97', '网红营销', 'Influencer Marketing', '网红营销', '跨境推广', 'Influencer-Marketing', 'Marketing de Influencers', 'Marketing d''influence', 'インフルエンサーマーケティング', 'Marketing de influência', 'Маркетинг влияния', '網紅營銷'), 
('98', 'EDM营销', 'EDM Marketing', 'EDM营销', '跨境推广', 'EDM-Marketing', 'Marketing EDM', 'Marketing EDM', 'EDMマーケティング', 'Marketing EDM', 'EDM маркетинг', 'EDM營銷'), 
('99', '账号购买', 'Account Purchase', '账号购买', '社媒资源', 'Kontoerwerb', 'Compra de cuentas', 'Achat de cuentas', 'アカウント購入', 'Compra de conta', 'Покупка аккаунтов', '帳號購買'), 
('100', '涨粉平台', 'Follower Growth Platform', '涨粉平台', '社媒资源', 'Follower-Wachstumsplattform', 'Plataforma de crecimiento de seguidores', 'Plateforme de croissance des abonnés', 'フォロワー成長プラットフォーム', 'Plataforma de crescimento de seguidores', 'Платформа роста подписчиков', '增粉平台'), 
('101', '全球VPS', 'Global VPS', '全球VPS', '全球网络', 'Globales VPS', 'VPS global', 'VPS mondial', 'グローバルVPS', 'VPS global', 'Глобальный VPS', '全球VPS'), 
('102', '中国VPS', 'China VPS', '中国VPS', '全球网络', 'China VPS', 'VPS de China', 'VPS de Chine', '中国VPS', 'VPS da China', 'Китайский VPS', '中國VPS'), 
('103', '全球IP代理', 'Global IP Proxy', '全球IP代理', '全球网络', 'Globaler IP-Proxy', 'Proxy IP global', 'Proxy IP mondial', 'グローバルIPプロキシ', 'Proxy IP global', 'Глобальный IP-прокси', '全球IP代理'), 
('104', '域名注册', 'Domain Registration', '域名注册', '全球网络', 'Domainregistrierung', 'Registro de dominio', 'Enregistrement de domaine', 'ドメイン登録', 'Registro de domínio', 'Регистрация домена', '域名註冊'), 
('105', '2FA短信验证码发送', '2FA SMS Code Sending', '2FA短信验证码发送', '全球接码', '2FA SMS-Versand', 'Envío de código SMS 2FA', 'Envoi de code SMS 2FA', '2FA SMS コード送信', 'Envio de código SMS 2FA', 'Отправка SMS-кода 2FA', '2FA簡訊驗證碼發送'), 
('106', '短信接码', 'SMS Receiving', '短信接码', '全球接码', 'SMS erhalten', 'Recepción de SMS', 'Réception de SMS', 'SMS受信', 'Recepção de SMS', 'Получение SMS', '簡訊接收'), 
('107', '虚拟邮箱', 'Virtual Mailbox', '虚拟邮箱', '全球接码', 'Virtuelles Postfach', 'Buzón Virtual', 'Boîte aux lettres virtuelle', 'バーチャルメールボックス', 'Caixa de Correio Virtual', 'Виртуальная почтовая ящик', '虛擬郵箱'), 
('108', '区块链媒体', 'Blockchain Media', '区块链媒体', '数字货币', 'Blockchain-Medien', 'Medios de Blockchain', 'Médias de Blockchain', 'ブロックチェーンメディア', 'Mídia Blockchain', 'Блокчейн СМИ', '區塊鏈媒體'), 
('109', '财经新闻', 'Finance News', '财经新闻', '数字货币', 'Finanznachrichten', 'Noticias financieras', 'Actualités financières', '経済ニュース', 'Notícias financeiras', 'Финансовые новости', '財經新聞'), 
('110', '市场数据', 'Market Data', '市场数据', '数字货币', 'Marktdaten', 'Datos del mercado', 'Données du marché', '市場データ', 'Dados de mercado', 'Рыночные данные', '市場數據'), 
('111', 'NFT工具', 'NFT Tools', 'NFT工具', '数字货币', 'NFT-Werkzeuge', 'Herramientas NFT', 'Outils NFT', 'NFTのツール', 'Ferramentas NFT', 'Инструменты NFT', 'NFT工具'), 
('112', '交易所', 'Exchange', '交易所', '数字货币', 'Börse', 'Intercambio', 'Échange', '取引所', 'Câmbio', 'Биржа', '交易所'), 
('113', '钱包', 'Wallet', '钱包', '数字货币', 'Brieftasche', 'Billetera', 'Portefeuille', '財布', 'Carteira', 'Кошелек', '錢包'), 
('114', '跨境支付', 'Cross-border Payment', '跨境支付', '跨境金融', 'Grenzüberschreitende Zahlung', 'Pago transfronterizo', 'Paiement transfrontalier', '国境を越えた支払い', 'Pagamento transfronteiriço', 'Трансграничный платеж', '跨境支付'), 
('115', 'FB常用工具', 'FB Common Tools', 'FB常用工具', 'Facebook', 'FB-Alltagswerkzeuge', 'Herramientas comunes de FB', 'Outils courants de FB', 'FBの一般的なツール', 'Ferramentas comuns do FB', 'Обычные инструменты FB', 'FB常用工具'), 
('116', 'FB申诉链接', 'FB Appeal Link', 'FB申诉链接', 'Facebook', 'FB-Berufungslink', 'Enlace de apelación de FB', 'Lien d''appel de FB', 'FBの申し立てリンク', 'Link de apelação do FB', 'Ссылка на апелляцию FB', 'FB申訴連結'), 
('117', 'FB官方资料', 'FB Official Information', 'FB官方资料', 'Facebook', 'FB offizielle Informationen', 'Información oficial de FB', 'Informations officielles de FB', 'FB公式情報', 'Informações oficiais do FB', 'Официальная информация FB', 'FB官方資料'), 
('118', 'FB广告工具', 'FB Advertising Tools', 'FB广告工具', 'Facebook', 'FB-Werbetools', 'Herramientas publicitarias de FB', 'Outils publicitaires de FB', 'FB広告ツール', 'Ferramentas publicitárias do FB', 'Рекламные инструменты FB', 'FB廣告工具'), 
('119', 'Google常用', 'Google Common Tools', 'Google常用', 'Google', 'Google-Alltagswerkzeuge', 'Herramientas comunes de Google', 'Outils courants de Google', 'Googleの一般的なツール', 'Ferramentas comuns do Google', 'Обычные инструменты Google', 'Google常用'), 
('120', '谷歌插件', 'Google Plugins', '谷歌插件', 'Google', 'Google-Plugins', 'Complementos de Google', 'Extensions Google', 'Googleプラグイン', 'Complementos do Google', 'Плагины Google', '谷歌插件'), 
('121', '关键词工具', 'Keyword Tools', '关键词工具', 'Google', 'Schlüsselwortwerkzeuge', 'Herramientas de palabras clave', 'Outils de mots-clés', 'キーワードツール', 'Ferramentas de palavras-chave', 'Инструменты ключевых слов', '關鍵詞工具'), 
('122', 'SEO工具', 'SEO Tools', 'SEO工具', 'Google', 'SEO-Werkzeuge', 'Herramientas de SEO', 'Outils de SEO', 'SEOツール', 'Ferramentas de SEO', 'Инструменты SEO', 'SEO工具'), 
('123', '广告监测', 'Ad Monitoring', '广告监测', '营销工具', 'Werbeüberwachung', 'Monitoreo de anuncios', 'Suivi des annonces', '広告モニタリング', 'Monitoramento de anúncios', 'Мониторинг рекламы', '廣告監測'), 
('124', '追踪系统', 'Tracking System', '追踪系统', '营销工具', 'Verfolgungssystem', 'Sistema de seguimiento', 'Système de suivi', 'トラッキングシステム', 'Sistema de rastreamento', 'Система отслеживания', '追蹤系統'), 
('125', 'Cloak工具', 'Cloaking Tools', 'Cloak工具', '营销工具', 'Cloaking-Tools', 'Herramientas de cloaking', 'Outils de masquage', 'Cloakツール', 'Ferramentas de cloaking', 'Инструменты Cloaking', 'Cloak工具'), 
('126', '检测优化', 'Optimization Tools', '检测优化', '营销工具', 'Optimierungswerkzeuge', 'Herramientas de optimización', 'Outils d''optimisation', '最適化ツール', 'Ferramentas de otimização', 'Инструменты оптимизации', '檢測優化'), 
('130', 'Lander制作', 'Landing Page Creation', 'Lander制作', '内容制作', 'Landerstellung', 'Creación de páginas de aterrizaje', 'Création de pages d''atterrissage', 'ランディングページ制作', 'Criação de páginas de destino', 'Создание целевых страниц', 'Lander製作'), 
('131', '文案工具', 'Copywriting Tools', '文案工具', '内容制作', 'Textwerkzeuge', 'Herramientas de redacción', 'Outils de rédaction', 'コピーライティングツール', 'Ferramentas de redação', 'Копирайтинг инструменты', '文案工具'), 
('132', '素材编辑', 'Material Editing', '素材编辑', '内容制作', 'Materialbearbeitung', 'Edición de material', 'Édition de matériel', '素材編集', 'Edição de material', 'Редактирование материалов', '素材編輯'), 
('133', '图库网站', 'Stock Photo Websites', '图库网站', '内容制作', 'Bilddatenbank-Websites', 'Sitios web de fotos de stock', 'Sites de photos libres de droits', 'ストックフォトサイト', 'Sites de fotos de estoque', 'Стоковые фотосайты', '圖庫網站'), 
('134', 'Logo设计', 'Logo Design', 'Logo设计', '内容制作', 'Logo-Design', 'Diseño de logotipos', 'Conception de logo', 'ロゴデザイン', 'Design de logotipos', 'Дизайн логотипов', 'Logo設計'), 
('135', '视频下载', 'Video Downloading', '视频下载', '内容制作', 'Video-Download', 'Descarga de video', 'Téléchargement vidéo', '動画ダウンロード', 'Download de vídeo', 'Загрузка видео', '影片下載'), 
('136', '软件开发', 'Software Development', '软件开发', '技术交流', 'Software-Entwicklung', 'Desarrollo de software', 'Développement de logiciels', 'ソフトウェア開発', 'Desenvolvimento de software', 'Разработка программного обеспечения', '軟體開發'), 
('137', '逆向安全', 'Reverse Security', '逆向安全', '技术交流', 'Reverse-Sicherheit', 'Seguridad inversa', 'Sécurité inversée', 'リバースセキュリティ', 'Segurança reversa', 'Обратная безопасность', '逆向安全'), 
('138', '主机交流', 'Hosting Discussion', '主机交流', '技术交流', 'Hosting-Diskussion', 'Discusión de hosting', 'Discussion sur l'hébergement', 'ホスティングディスカッション', 'Discussão de hospedagem', 'Обсуждение хостинга', '主機交流'), 
('139', '脚本工具', 'Scripting Tools', '脚本工具', '营销工具', 'Skriptwerkzeuge', 'Herramientas de scripting', 'Outils de script', 'スクリプトツール', 'Ferramentas de script', 'Инструменты скриптов', '腳本工具'), 
('140', '云手机', 'Cloud Phone', '云手机', '营销工具', 'Cloud-Telefon', 'Teléfono en la nube', 'Téléphone cloud', 'クラウドフォン', 'Telefone em Nuvem', 'Облачный телефон', '雲端手機'), 
('141', '模拟器', 'Emulator', '模拟器', '营销工具', 'Emulator', 'Emulador', 'Émulateur', 'エミュレーター', 'Emulador', 'Эмулятор', '模擬器'), 
('142', '新机工具', 'New Device Tools', '新机工具', '营销工具', 'Neue Gerätewerkzeuge', 'Herramientas de nuevos dispositivos', 'Outils pour nouveaux appareils', '新しいデバイスツール', 'Ferramentas de novos dispositivos', 'Инструменты новых устройств', '新機工具'), 
('143', '电商平台', 'E-commerce Platform', '电商平台', '跨境电商', 'E-Commerce-Plattform', 'Plataforma de comercio electrónico', 'Plateforme e-commerce', '電子商取引プラットフォーム', 'Plataforma de comércio eletrônico', 'Платформа электронной торговли', '電商平台'), 
('144', '独立站', 'Independent Site', '独立站', '跨境电商', 'Unabhängige Seite', 'Sitio independiente', 'Site indépendant', '独立したサイト', 'Site independente', 'Независимый сайт', '獨立站'), 
('145', '选品分析', 'Product Analysis', '选品分析', '跨境电商', 'Produktanalyse', 'Análisis de productos', 'Analyse de produits', '製品分析', 'Análise de produtos', 'Анализ продукции', '選品分析'), 
('146', 'Deals平台', 'Deals Platform', 'Deals平台', '跨境电商', 'Deals-Plattform', 'Plataforma de ofertas', 'Plateforme de bonnes affaires', 'お買い得プラットフォーム', 'Plataforma de ofertas', 'Платформа сделок', 'Deals平台'), 
('147', '广告代理', 'Ad Agency', '广告代理', '跨境服务', 'Werbeagentur', 'Agencia de publicidad', 'Agence de publicité', '広告代理店', 'Agência de Publicidade', 'Рекламное агентство', '廣告代理'), 
('148', '常用ERP', 'Common ERP', '常用ERP', '跨境服务', 'Häufige ERP', 'ERP común', 'ERP commun', '一般的ERP', 'ERP comum', 'Обычный ERP', '常用ERP'), 
('149', '物流货代', 'Logistics Freight Forwarder', '物流货代', '跨境服务', 'Logistik-Frachtführer', 'Agente de logística', 'Transitaire logistique', '物流フォワーダー', 'Agente de logística', 'Логистический экспедитор', '物流貨代'), 
('150', '货源网站', 'Source Website', '货源网站', '跨境服务', 'Lieferantenwebsite', 'Sitio de proveedores', 'Site de fournisseurs', '供給元のウェブサイト', 'Site de fornecedores', 'Сайт поставщиков', '貨源網站'), 
('151', '国内论坛', 'Domestic Forum', '国内论坛', '跨境资讯', 'Inland-Forum', 'Foro doméstico', 'Forum national', '国内フォーラム', 'Fórum doméstico', 'Внутренний форум', '國內論壇'), 
('152', '国外论坛', 'Foreign Forum', '国外论坛', '跨境资讯', 'Ausland-Forum', 'Foro extranjero', 'Forum étranger', '海外フォーラム', 'Fórum estrangeiro', 'Иностранный форум', '國外論壇'), 
('153', 'affiate联盟', 'Affiliate Alliance', 'affiate联盟', '跨境资讯', 'Affiliierte Allianz', 'Alianza de afiliados', 'Alliance affiliés', 'アフィリエイト連盟', 'Aliança de afiliados', 'Аффилированный альянс', 'affiate聯盟'), 
('154', '代理检测', 'Proxy Detection', '代理检测', '网络资源', 'Proxy-Erkennung', 'Detección de proxy', 'Détection de proxy', 'プロキシ検出', 'Detecção de proxy', 'Обнаружение прокси', '代理檢測'), 
('155', '指纹检测', 'Fingerprint Detection', '指纹检测', '网络资源', 'Fingerprint-Erkennung', 'Detección de huellas dactilares', 'Détection des empreintes digitales', '指紋検出', 'Detecção de impressões digitais', 'Обнаружение отпечатков', '指紋檢測'), 
('156', '静态代理', 'Static Proxy', '静态代理', '网络资源', 'Statischer Proxy', 'Proxy estático', 'Proxy statique', '静的プロキシ', 'Proxy estático', 'Статический прокси', '靜態代理'), 
('157', '网络加速器', 'Network Accelerator', '网络加速器', '网络资源', 'Netzwerkbeschleuniger', 'Acelerador de red', 'Accélérateur réseau', 'ネットワークアクセラレーター', 'Acelerador de rede', 'Сетевой ускоритель', '網絡加速器'), 
('158', 'TikTok直播专线', 'TikTok Live Line', 'TikTok直播专线', '网络资源', 'TikTok-Liveline', 'Línea en vivo de TikTok', 'Ligne en direct TikTok', 'TikTokライブライン', 'Linha ao vivo do TikTok', 'Линия TikTok', 'TikTok直播專線'), 
('159', '动态代理', 'Dynamic Proxy', '动态代理', '网络资源', 'Dynamischer Proxy', 'Proxy dinámico', 'Proxy dynamique', '動的プロキシ', 'Proxy dinâmico', 'Динамический прокси', '動態代理'), 
('160', 'VPS推荐', 'VPS Recommendation', 'VPS推荐', '网络资源', 'VPS-Empfehlung', 'Recomendación de VPS', 'Recommandation VPS', 'VPS推奨', 'Recomendação de VPS', 'Рекомендация VPS', 'VPS推薦'), 
('161', '电商平台', 'E-commerce Platform', '电商平台', '跨境服务', 'E-Commerce-Plattform', 'Plataforma de comercio electrónico', 'Plateforme e-commerce', '電子商取引プラットフォーム', 'Plataforma de e-commerce', 'Платформа электронной коммерции', '電商平台'), 
('162', '广告开户', 'Ad Account Opening', '广告开户', '营销工具', 'Werbekontoeröffnung', 'Apertura de cuenta publicitaria', 'Ouverture de compte publicitaire', '広告アカウント開設', 'Abertura de conta de anúncios', 'Открытие рекламной учетной записи', '廣告開戶'), 
('163', '广告检测', 'Ad Detection', '广告检测', '营销工具', 'Werbeerkennung', 'Detección de anuncios', 'Détection d''annonces', '広告検出', 'Detecção de anúncios', 'Обнаружение рекламы', '廣告檢測'), 
('164', '推荐工具', 'Recommendation Tool', '推荐工具', '综合软件', 'Empfehlungswerkzeug', 'Herramienta de recomendación', 'Outil de recommandation', '推薦ツール', 'Ferramenta de recomendação', 'Инструмент рекомендаций', '推薦工具'), 
('165', '效率工具', 'Efficiency Tool', '效率工具', '综合软件', 'Effizienzwerkzeug', 'Herramienta de eficiencia', 'Outil d''efficacité', '効率ツール', 'Ferramenta de eficiência', 'Инструмент эффективности', '效率工具'), 
('166', '虚拟信用卡', 'Virtual Credit Card', '虚拟信用卡', '跨境金融', 'Virtuelle Kreditkarte', 'Tarjeta de crédito virtual', 'Carte de crédit virtuelle', 'バーチャルクレジットカード', 'Cartão de crédito virtual', 'Виртуальная кредитная карта', '虛擬信用卡'), 
('167', '财税合规', 'Tax Compliance', '财税合规', '跨境金融', 'Steuerliche Regelkonformität', 'Cumplimiento tributario', 'Conformité fiscale', '税務コンプライアンス', 'Conformidade tributária', 'Налоговое соответствие', '財稅合規'), 
('168', '跨境支付', 'Cross-Border Payment', '跨境支付', '跨境金融', 'Grenzüberschreitende Zahlung', 'Pago transfronterizo', 'Paiement transfrontalier', '越境決済', 'Pagamento transfronteiriço', 'Трансграничный платеж', '跨境支付'), 
('169', '跨境贷款', 'Cross-Border Loan', '跨境贷款', '跨境金融', 'Grenzüberschreitender Kredit', 'Préstamo transfronterizo', 'Prêt transfrontalier', '越境ローン', 'Empréstimo transfronteiriço', 'Трансграничный кредит', '跨境貸款'), 
('170', '国际短信', 'International SMS', '国际短信', '跨境资讯', 'Internationale SMS', 'SMS internacional', 'SMS international', '国際SMS', 'SMS internacional', 'Международные SMS', '國際短信'), 
('171', '虚拟邮箱', 'Virtual Mailbox', '虚拟邮箱', '跨境资讯', 'Virtuelles Postfach', 'Buzón virtual', 'Boîte aux lettres virtuelle', '仮想メールボックス', 'Caixa de correio virtual', 'Виртуальный почтовый ящик', '虛擬郵箱'), 
('172', '虚拟资料生成器', 'Virtual Data Generator', '虚拟资料生成器', '跨境资讯', 'Virtueller Daten-Generator', 'Generador de datos virtual', 'Générateur de données virtuelles', '仮想データ生成器', 'Gerador de dados virtual', 'Виртуальный генератор данных', '虛擬資料生成器'), 
('173', '图库编辑', 'Image Editing', '图库编辑', '内容制作', 'Bildbearbeitung', 'Edición de imágenes', 'Édition d''images', '画像編集', 'Edição de imagens', 'Редактирование изображений', '圖庫編輯'), 
('174', 'lander制作', 'Lander Production', 'lander制作', '内容制作', 'Lander-Produktion', 'Producción de lander', 'Production de lander', 'ランダー制作', 'Produção de lander', 'Производство ландеров', 'lander制作'), 
('175', 'logo设计', 'Logo Design', 'logo设计', '内容制作', 'Logo-Design', 'Diseño de logotipos', 'Conception de logo', 'ロゴデザイン', 'Design de logotipo', 'Дизайн логотипа', 'logo設計'), 
('176', '网红营销', 'Influencer Marketing', '网红营销', '跨境推广', 'Influencer-Marketing', 'Marketing de influencers', 'Marketing d''influence', 'インフルエンサーマーケティング', 'Marketing de influenciadores', 'Маркетинг через влияние', '網紅營銷'), 
('177', '社交媒体', 'Social Media', '社交媒体', '跨境推广', 'Soziale Medien', 'Redes sociales', 'Médias sociaux', 'ソーシャルメディア', 'Mídias sociais', 'Социальные сети', '社交媒體'), 
('178', 'EDM营销', 'EDM Marketing', 'EDM营销', '跨境推广', 'EDM-Marketing', 'Marketing EDM', 'Marketing EDM', 'EDMマーケティング', 'Marketing EDM', 'EDM маркетинг', 'EDM營銷'), 
('179', '社交营销', 'Social Marketing', '社交营销', '跨境推广', 'Sozialmarketing', 'Marketing social', 'Marketing social', 'ソーシャルマーケティング', 'Marketing social', 'Социальный маркетинг', '社交營銷'), 
('180', '内容素材', 'Content Materials', '内容素材', 'TikTok', 'Inhaltsmaterial', 'Materiales de contenido', 'Matériaux de contenu', 'コンテンツ素材', 'Materiais de conteúdo', 'Материалы контента', '內容素材'), 
('181', 'TK选品', 'TK Selection', 'TK选品', 'TikTok', 'TK-Auswahl', 'Selección de TK', 'Sélection TK', 'TK選定', 'Seleção TK', 'Выбор TK', 'TK選品'), 
('182', '培训机构', 'Training Institute', '培训机构', 'TikTok', 'Schulungseinrichtung', 'Instituto de formación', 'Institut de formation', 'トレーニング機関', 'Instituto de Treinamento', 'Учебное заведение', '培訓機構'), 
('183', 'TK分销', 'TK Distribution', 'TK分销', 'TikTok', 'TK-Verteilung', 'Distribución de TK', 'Distribution TK', 'TK配信', 'Distribuição de TK', 'Распределение TK', 'TK分銷'), 
('184', '内容分析', 'Content Analysis', '内容分析', 'TikTok', 'Inhaltsanalyse', 'Análisis de contenido', 'Analyse de contenu', 'コンテンツ分析', 'Análise de conteúdo', 'Анализ контента', '內容分析'), 
('185', '视频剪辑', 'Video Editing', '视频剪辑', 'TikTok', 'Videobearbeitung', 'Edición de video', 'Montage vidéo', 'ビデオ編集', 'Edição de vídeo', 'Редактирование видео', '視頻剪輯'), 
('186', 'TK物流', 'TK Logistics', 'TK物流', 'TikTok', 'TK-Logistik', 'Logística de TK', 'Logistique de TK', 'TKロジスティクス', 'Logística de TK', 'Логистика TK', 'TK物流'), 
('187', 'ERP', 'ERP', 'ERP', 'TikTok', 'ERP', 'ERP', 'ERP', 'ERP', 'ERP', 'ERP', 'ERP'), 
('188', '平台入口', 'Platform Access', '平台入口', 'TikTok', 'Plattformzugang', 'Acceso a la plataforma', 'Accès à la plateforme', 'プラットフォームアクセス', 'Acesso à plataforma', 'Доступ к платформе', '平台入口'), 
('189', '流量运营', 'Traffic Operations', '流量运营', 'TikTok', 'Traffic-Operationen', 'Operaciones de tráfico', 'Opérations de trafic', 'トラフィック運営', 'Operações de tráfego', 'Операции с трафиком', '流量運營'), 
('190', '网红平台', 'Influencer Platform', '网红平台', 'TikTok', 'Influencer-Plattform', 'Plataforma de influencers', 'Plateforme d''influenceurs', 'インフルエンサー プラットフォーム', 'Plataforma de influenciadores', 'Платформа влияния', '網紅平台'), 
('191', '采集选品', 'Product Selection', '采集选品', '独立站', 'Produktwahl', 'Selección de productos', 'Sélection de produits', '製品選択', 'Seleção de produtos', 'Выбор продукта', '採集選品'), 
('192', '独立站物流', 'Independent Site Logistics', '独立站物流', '独立站', 'Logistik für unabhängige Websites', 'Logística de sitios independientes', 'Logistique pour sites indépendants', '独立サイト物流', 'Logística de sites independentes', 'Логистика независимого сайта', '獨立站物流'), 
('193', '独立建站', 'Independent Site Building', '独立建站', '独立站', 'Unabhängige Website-Erstellung', 'Construcción de sitios independientes', 'Création de sites indépendants', '独立サイトの構築', 'Criação de sitios independentes', 'Создание независимого сайта', '獨立建站'), 
('194', 'AI办公工具', 'AI Office Tools', 'AI办公工具', 'AI工具', 'KI-Bürowerkzeuge', 'Herramientas de oficina de IA', 'Outils de bureau IA', 'AIオフィスツール', 'Ferramentas de escritório IA', 'Инструменты офиса AI', 'AI辦公工具'), 
('195', '帐号购买', 'Account Purchase', '帐号购买', '社媒资源', 'Kontoerwerb', 'Compra de cuentas', 'Achat de cuentas', 'アカウント購買', 'Compra de conta', 'Покупка аккаунта', '帳號購買'), 
('196', 'Switzerland', 'Switzerland', 'Switzerland', 'proxy', 'Schweiz', 'Suiza', 'Suisse', 'スイス', 'Suíça', 'Швейцария', 'Switzerland'), 
('197', '健身运动工具', 'Fitness Tool', '健身运动工具', '实用工具', 'Fitnesswerkzeug', 'Herramienta de fitness', 'Outil de fitness', 'フィットネスツール', 'Ferramenta de fitness', 'Фитнес- инструмент', '健身運動工具'), 
('198', 'AI开发者工具', 'AI Developer Tool', 'AI开发者工具', 'AI工具', 'AI-Entwicklerwerkzeug', 'Herramienta para desarrolladores de IA', 'Outil pour développeurs IA', 'AI開發者工具', 'Ferramenta para desenvolvedores de IA', 'Инструмент для разработчиков ИИ', 'AI開發者工具');